# Generated by Django 3.2.12 on 2022-02-20 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_auto_20220220_0822"),
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="video_id",
        ),
        migrations.AddField(
            model_name="playlist",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlist_featured",
                to="videos.video",
            ),
        ),
        migrations.CreateModel(
            name="PlaylistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playlists.playlist",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="videos.video"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="playlist",
            name="videos",
            field=models.ManyToManyField(
                blank=True,
                related_name="playlist_item",
                through="playlists.PlaylistItem",
                to="videos.Video",
            ),
        ),
    ]
