# Generated by Django 3.2.12 on 2022-02-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='video_id',
        ),
    ]
