# Generated by Django 3.2.12 on 2022-02-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_auto_20220220_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShowProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Tv Show',
                'verbose_name_plural': 'Tv Shows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
        migrations.CreateModel(
            name='TvShowSeasonProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
