# Generated by Django 3.2.12 on 2022-02-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_alter_video_video_id'),
        ('playlists', '0004_playlist_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_playlist', to='videos.video'),
        ),
    ]
