# Generated by Django 3.2.12 on 2022-02-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0006_playlist_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieProxy",
            fields=[],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("playlists.playlist",),
        ),
    ]
